export const staticRoutes: AppRoute.RowRoute[] = [
  {
    name: 'dashboard',
    path: '/dashboard',
    title: '仪表盘',
    requiresAuth: true,
    icon: 'icon-park-outline:analysis',
    menuType: 'dir',
    componentPath: null,
    id: 1,
    pid: null,
  },
  {
    name: 'workbench',
    path: '/dashboard/workbench',
    title: '工作台',
    requiresAuth: true,
    icon: 'icon-park-outline:alarm',
    pinTab: true,
    menuType: 'page',
    componentPath: '/dashboard/workbench/index.vue',
    id: 2,
    pid: 1,
  },
  {
    name: 'monitor',
    path: '/dashboard/monitor',
    title: '监控页',
    requiresAuth: true,
    icon: 'icon-park-outline:anchor',
    menuType: 'page',
    componentPath: '/dashboard/monitor/index.vue',
    id: 3,
    pid: 1,
  },
  {
    name: 'client',
    path: '/client',
    title: '客户管理',
    requiresAuth: true,
    icon: 'icon-park-outline:user',
    menuType: 'page',
    componentPath: '/client/index.vue',
    id: 4,
    pid: 0,
  },
  {
    name: 'clientList',
    path: '/client/list',
    title: '客户列表',
    requiresAuth: true,
    menuType: 'page',
    componentPath: '/client/list.vue',
    id: 5,
    pid: 4,
  },
  {
    name: 'palettes',
    path: '/palettes',
    title: '色板管理',
    requiresAuth: true,
    icon: 'icon-park-outline:platte',
    menuType: 'page',
    componentPath: '/palettes/index.vue',
    id: 6,
    pid: 0,
  },
  {
    name: 'palettesList',
    path: '/palettes/list',
    title: '色板列表',
    requiresAuth: true,
    menuType: 'page',
    componentPath: '/palettes/list.vue',
    id: 7,
    pid: 6,
  },
  {
    name: 'setting',
    path: '/setting',
    title: '系统设置',
    requiresAuth: true,
    icon: 'icon-park-outline:setting',
    menuType: 'dir',
    componentPath: null,
    id: 35,
    pid: null,
  },
  {
    name: 'accountSetting',
    path: '/setting/account',
    title: '用户设置',
    requiresAuth: true,
    icon: 'icon-park-outline:every-user',
    componentPath: '/setting/account/index.vue',
    id: 36,
    pid: 35,
  },
  {
    name: 'menuSetting',
    path: '/setting/menu',
    title: '菜单设置',
    requiresAuth: true,
    icon: 'icon-park-outline:application-menu',
    componentPath: '/setting/menu/index.vue',
    id: 38,
    pid: 35,
  },
  {
    name: 'userCenter',
    path: '/userCenter',
    title: '个人中心',
    requiresAuth: true,
    icon: 'carbon:user-avatar-filled-alt',
    componentPath: '/demo/userCenter/index.vue',
    id: 39,
    pid: null,
  },
]
